### ISSUE TITLE
Exclusive access not assigned to current Thread

### ISSUE THREAD

**Issue by NavnathDodeg** [eclipse-keyple/keyple-plugin-pcsc-java-lib#13]
java.lang.IllegalStateException: Exclusive access not assigned to current Thread
        at java.smartcardio/sun.security.smartcardio.CardImpl.endExclusive(CardImpl.java:226)
        at org.eclipse.keyple.plugin.pcsc.AbstractPcscReaderAdapter.setSharingMode(AbstractPcscReaderAdapter.java:336)

**Comment by jeanpierrefortune** [comment]
Thank you for submitting the issue on our GitHub repository. 
However, without any details or questions, we are unable to address the problem.
Regards
